function [] = SetGlobalVariables(ex_num,el,mean_method, bool_alpha_theta, low_rank_approx_method)
global SETTINGS;

SETTINGS.EX_NUM = ex_num;
SETTINGS.NOISE = el;
SETTINGS.MEAN_METHOD = mean_method;
SETTINGS.BOOL_ALPHA_THETA = bool_alpha_theta;
SETTINGS.LOW_RANK_APPROXIMATION_METHOD = low_rank_approx_method;

SETTINGS.SEED = 1024;
SETTINGS.THRESHOLD = 4;
SETTINGS.PLOT_GRAPHS = 'n';
SETTINGS.BOOL_NOISE = 'y';

SETTINGS.MAX_ERROR_SNTLN = 1e-15;
SETTINGS.MAX_ITE_SNTLN = 100;
SETTINGS.MAX_ERROR_DECONVOLUTIONS = 1e-10;
SETTINGS.MAX_ITERATIONS_DECONVOLUTIONS = 20;
SETTINGS.DECONVOLVE_METHOD = 'Batch';


end




